sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 222222
  alioss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    access-key-id: ${ALIYUNN_ACCESS_KEY_ID}
    access-key-secret: ${ALIYUNN_ACCESS_KEY_SECRET}
    bucket-name: tfory
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  wechat:
    appid: wxcce47f315db93932
    secret: f1bdb743a6f2ecf4825bb7447a25ae72