sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 222222
  alioss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    access-key-id: ${ALIYUNN_ACCESS_KEY_ID}
    access-key-secret: ${ALIYUNN_ACCESS_KEY_SECRET}
    bucket-name: tfory
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  wechat:
    appid: wxcce47f315db93932
    secret: f1bdb743a6f2ecf4825bb7447a25ae72
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://www.weixin.qq.com/wxpay/pay.php
    refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php